### PR TITLE
making inputView state immutable but with a copyWith method

### PR DESCRIPTION
**Pull request by itamarsch**
@giladwo This feels something you would want me to do (I think you wanted me to do this in the past) I'm not really sure I implemented this in the best way  do you approve of how I implemented this?

### CODE REVIEW

**Comment by giladwo** [comment]
@itamarsch What do we get here except a longer and more convoluted way to do the same thing?

Don't make changes you don't believe are improvements.

I'm all for reducing mutation to minimum, but in a way that makes sense and enables a more elegant solution, which is not the case here.
To get the gist of it, you should really watch talks like [Propositions as Types](https://www.youtube.com/watch?v=IOiZatlZtGU) and learn to think differently. A really good place to start is to learn [Elm](https://www.elm-lang.org) - shouldn't take you more than a weekend, and can greatly widen your perspective (once you get comfortable with its principles). Just ask @NoamPrag or me (I'll be more available next week during the holiday break).

**Comment by itamarsch** [comment]
> @itamarsch What do we get here except a longer and more convoluted way to do the same thing?
> 
> Don't make changes you don't believe are improvements.
> 
> I'm all for reducing mutation to minimum, but in a way that makes sense and enables a more elegant solution, which is not the case here. To get the gist of it, you should really watch talks like [Propositions as Types](https://www.youtube.com/watch?v=IOiZatlZtGU) and learn to think differently. A really good place to start is to learn [Elm](https://www.elm-lang.org) - shouldn't take you more than a weekend, and can greatly widen your perspective (once you get comfortable with its principles). Just ask @NoamPrag or me (I'll be more available next week during the holiday break).

I just watched Propositions as Types and I didn't really understand the start where he compared lamda calculus and logic and I didn't understand what makes things that were discovered better than things that were invented. The whole talk just confused me and I didn't really understand how this relates to programming.

**Comment by itamarsch** [comment]
And as for elm I guess I'm already a master of the craft 😎

https://user-images.githubusercontent.com/71348842/163029665-dd07c7c1-19de-4867-a98a-452aba1c9298.mp4

**Comment by giladwo** [comment]
> > @itamarsch What do we get here except a longer and more convoluted way to do the same thing?
> > 
> > Don't make changes you don't believe are improvements.
> > 
> > I'm all for reducing mutation to minimum, but in a way that makes sense and enables a more elegant solution, which is not the case here. To get the gist of it, you should really watch talks like [Propositions as Types](https://www.youtube.com/watch?v=IOiZatlZtGU) and learn to think differently. A really good place to start is to learn [Elm](https://www.elm-lang.org) - shouldn't take you more than a weekend, and can greatly widen your perspective (once you get comfortable with its principles). Just ask @NoamPrag or me (I'll be more available next week during the holiday break).
> 
> I just watched Propositions as Types and I didn't really understand the start where he compared lamda calculus and logic and I didn't understand what makes things that were discovered better than things that were invented. The whole talk just confused me and I didn't really understand how this relates to programming.

And so the journey begins 🙂

**Pull request closed without merging**
