### PR TITLE
Changing Team Search Box

### PR DESCRIPTION
**Pull request by ItayNaumann**

### CODE REVIEW

**Comment by ItayNaumann** [comment]
image
just added an option to send the initial team; currently not used in any place in the code but it needed it to run....

**Comment by ItayNaumann** [comment]
image
removed the controller and changed to teamSelectionMatches' new way of building

**Comment by ItayNaumann** [comment]
image
in pit view we just move teamSelectionMatches outside of the column and made the build without team method

**Comment by ItayNaumann** [comment]
image
in add fault we removed the LightTeam from the scope and just changed to the new way we use teamSelectionMatches

**Comment by ItayNaumann** [comment]
image
just made build with team, removed the controller and changed from onChange to onSelection and fixed a weird check

**Comment by ItayNaumann** [comment]
image
image
image
changed from having a lot of controllers to having a list of resets and set each reset in his defining teamSelectionMatches (cut up a bit of code cause its repetitive....)

**Comment by ItayNaumann** [comment]
image
image
removed the unnecessary state of the widget, made it only build the widget when it gets team and changed to new teamSelectionFuture

**Comment by ItayNaumann** [comment]
image
changing teamSelectionFuture to get a reset function, build with and without team functions, resetSearchBox function that resets the team and the textBox ,initialTeam and an onSelected function

**Comment by ItayNaumann** [comment]
image
image
image
team search box get all the things that teamSelectionFuture and makes a searchBox that returns a reset function to let us reset the searchBox from another scope, and building it 1 of 3 different ways: with a selected team, with the initial team and with no team.

**Comment by ItayNaumann** [comment]
image
changing teamSelectionMatches to get a building searchBox with and without team, an on selected function and an initial team (for some reason not showing it here).

**Comment by ItayNaumann** [comment]
@Team1690/scouting can some1 review the changes? ik its a lot but it need to be merged...

**Review by itamarsch — APPROVED** [review]
I worked on this with you I have seen all the code before looks good

**Comment by ItayNaumann** [comment]
There are one or 2 problems with this pr but i think we should just merge it and make issues about them that i'll work on them rn, @giladwo i just want you to look at the changes, to maybe spot any big mistakes we haven't caught.

**Comment by amitcha06** [comment]
Overall looks good, then again, i wasnt present during the specifications for this PR and didnt work on it at all. Therefore im not approving and would like Gilad/Itach to review instead

**Comment by amitcha06** [comment]
> There are one or 2 problems with this pr but i think we should just merge it and make issues about them that i'll work on them rn, @giladwo i just want you to look at the changes, to maybe spot any big mistakes we haven't caught.

NO
we should never merge problematic (not working/has bugs) changes into master

**Comment by ItayNaumann** [comment]
this will merge only after @giladwo 's review and after we fix #386

**Pull request closed without merging**
