### PR TITLE
Linechart fixes

### PR DESCRIPTION
**Pull request by itamarsch**

### CODE REVIEW

**Comment by itamarsch** [comment]
fixes #112

**Comment by giladwo** [comment]
> fixes #112 @giladwo you opened this issue do you approve the way I fixed this?

Too many changes going on here, but you seem to get the main idea.
You could inherit the base instead of manually delegating inside `build`, but I'm all for avoiding inheritance so kudos.

**Comment by itamarsch** [comment]
I basically just made a base Widget with the common things that are in both LineCharts and made the differences between both charts parameters of the Widget

**Comment by itamarsch** [comment]
@Team1690/scouting can someone approve?

**Comment by itamarsch** [comment]
@Ido-Sobol @giladwo @GuyNoimark can someone approve this pr?

**Review by Ido-Sobol — APPROVED** [review]

**Pull request merged**
