### PR TITLE
making id querys into a single generic query

### PR DESCRIPTION
**Pull request by itamarsch**

### CODE REVIEW

**Comment by giladwo** [comment]
How is this an improvement?

**Comment by itamarsch** [comment]
I did this because of the amount of requests because we only have 60 requests per minute and I don't think making 6 requests on opening the app is very environment friendly

**Comment by giladwo** [comment]
Premature optimization is the root of all evil.
I stand by my previous comment.

**Comment by itamarsch** [comment]
I don't understand why we shouldn't optimize this when we can because no one wants the app not to work while a game is happening especially when we query on startup and dont let the app start without the query to succeed

**Comment by giladwo** [comment]
With these queries running only on startup, the benefit is negligible.
Thus, the disadvantages outweigh the slight improvement.
In other words, this change isn't enough to make a real difference.

If you're worried about approaching Hasura Cloud's free tier limit, grab a few scouters and simulate a real competition.
Experience a problem and then we can figure out what's the correct solution to the actual problem at hand.

Do not try to optimize without prior measurements. It's not productive at best, and harmful at worst.
Here's an example of such "optimization" going wrong: https://github.com/elm-community/list-extra/pull/140.

**Comment by itamarsch** [comment]
Ok sounds goods.
Also from a quick calculation on app opening there are 5 requests and there are 12 scouters per game (at most) and let's say they all open the app at the same time we are safe.

A problem might arise if one of the other scouting groups open the app or someone that isn't supposed to open the app opens the app but I don't really think that will happen and we will seen in two weeks if we need to change something

**Comment by itamarsch** [comment]
Actually I'm about to make it 6 requests on opening because I want to add add the match_type_id column to match_2022 and that needs another request for the id's of the types

**Comment by itamarsch** [comment]
I take it back we will face the limit and I think we should merge this pr because 24 requests per game is a alot better than 60

**Review by Ido-Sobol — APPROVED** [review]

**Pull request merged**
