### PR TITLE
Add teams color

### PR DESCRIPTION
**Pull request by GuyNoimark**
Source:
https://docs.google.com/spreadsheets/d/1WLysPiXo85B2k-hD5KY_sG4U6RQ9lFs4HvyEzExTqtI/edit#gid=0

### CODE REVIEW

**Comment by giladwo** [comment]
Why not just access the sheet directly?
https://pub.dev/packages/gsheets

**Comment by GuyNoimark** [comment]
We can do it. The problem I faced was to convert the RGB color values from the excel to flutter with the exact format that I could copy paste to VS code

```
1690: Color.fromARGB(255,0,0,200),
```

At the end I downloaded the file and used the =CONCAT text formula in excel

**Comment by giladwo** [comment]
> We can do it. The problem I faced was to convert the RGB color values from the excel to flutter with the exact format that I could copy paste to VS code
> 
> ```
> 1690: Color.fromARGB(255,0,0,200),
> ```

Isn't it easier to just use columns A, C, D, E or H, I, J, K?
It can be as simple as
```dart
Function<LightTeam, Color> crowdsourceColors() async {
  final GSheets gsheets = GSheets(...);
  final Spreadsheet spreadsheet = await gsheets.spreadsheet(...);
  final Worksheet sheet = spreadsheet.worksheetByTitle("Sheet1")
    ?? return (final LightTeam team) => Color.fromARGB(255, 1, 2, 3);  // some default color (or alternatively, throw)
  final Function<int, int> colorColumn(final int index) =>
    (final int team) => int.parse(sheet.values.value(column: index, row: team + 1));
  final Function<int, int> red = colorColumn(4);
  final Function<int, int> green = colorColumn(5);
  final Function<int, int> blue = colorColumn(6);
  return (final LightTeam team) => 
    Color.fromARGB(255, red(team.number), green(team.number), blue(team.number));
}
```
or as complicated as binary searching H.

**Comment by itamarsch** [comment]
I don't think using this package helps us that much it just complicates things and the sheets file probably not going to be changed (Guy found the that file on the chief delphi) I integrated this into the project for this feature to work I opened a different pr for the integration

**Pull request closed without merging**
