### PR TITLE
Revert "344 - Finished Queries' Technical Debt "

### PR DESCRIPTION
**Pull request by ItayNaumann**
Reverts Team1690/Scouting-Frontend#347

### CODE REVIEW

**Comment by giladwo** [comment]
@ItayNaumann why?

**Comment by ItayNaumann** [comment]
@giladwo I thought I needed to revert cause it didn't run, forgot that @amitcha06 is working on the problem

**Comment by ItayNaumann** [comment]
this feature breaks the app, i forgot to check it i merged into master, starting to work on that as soon as this is merged

**Comment by ItayNaumann** [comment]
it didn't let me name the commits normally so ill explain them here, the first one I just pulled everything from master except for id helpers, the second one I changed a long-lasting typo

**Review by amitcha06 — APPROVED** [review]
this issue should still be fixed, just make sure it works before merging next time :P

**Pull request merged**
