### PR TITLE
Updating team list

### PR DESCRIPTION
**Pull request by amitcha06**

### CODE REVIEW

**Review by ItayNaumann — APPROVED** [review]
just added the change to an e you missed, looks good other than that

**Review by itamarsch — DISMISSED** [review]

**Review by OmerPrag — APPROVED** [review]

**Comment by giladwo** [comment]
@amitcha06 @itamarsch @ItayNaumann join me in discord VC

**Comment by ItayNaumann** [comment]
image
change the vsCode settings (accessed by ctrl + shift + p) to work with the new formater @amitcha06

**Review by itamarsch — APPROVED** [review]

**Review by Ido-Sobol — APPROVED** [review]

**Comment by giladwo** [comment]
> image
> 
> change the vsCode settings (accessed by ctrl + shift + p) to work with the new formater @amitcha06 

You know, vscode has worksapace-scope settings, which can (and should) be versioned.

https://www.roboleary.net/vscode/2020/09/17/vscode-workspace-settings.html

**Pull request merged**
